# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
test_Array=np.array(np.arange(50))
test_Array[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
test_Array.shape

(50,)

5. Print the type of the previous array in question 3

In [5]:
test_Array.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [7]:
test_Array.ndim

1

8. Create a boolean array with all the True values

In [8]:
np.ones(10, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [9]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

10. Create a three dimensional array



In [10]:
np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
test_Array[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null=np.zeros(10)
null[4]=1
null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
np.ones((3,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5],dtype=np.float32)
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
arr1 =np.array([[1., 2., 3.],[4., 5., 6.]])                       
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
comparison = arr1 == arr2 
equal_arrays = comparison.all() 
equal_arrays

False

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr=np.arange(10)
[i for i in arr if i%2 == 1]

[1, 3, 5, 7, 9]

18. Replace all odd numbers to -1 from previous array

In [18]:
#arr=np.arange(10)
arr=[(-1 if i%2 == 1 else i) for i in arr]
arr

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[4:8]=np.arange(8,12)
arr

array([ 0,  1,  2,  3,  8,  9, 10, 11,  8,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
_2darr=np.ones((5,5))
_2darr[1:-1,1:-1]=0
_2darr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9],[10, 11, 12]])
np.where(arr2d > 4, 6, arr2d)

array([[1, 2, 3],
       [4, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0]=[77,88,77]
arr3d

array([[[77, 88, 77],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr=np.arange(10)
arr=arr.reshape(2,5)
arr[0]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
np.arange(10).reshape(2,5)[1]

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
np.arange(10).reshape(2,5)[:2,2]

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr10d=np.random.random_sample((10,10))
print("Min value: ",np.min(arr10d))
print("Max value: ",np.max(arr10d))

Min value:  0.010049845479097486
Max value:  0.9842784803914375


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
res = [index for index,(x,y) in enumerate(zip(a,b)) if x==y]
print("Value of {} match at index no. {}: ".format(np.intersect1d(a,b),res))

Value of [2 4] match at index no. [1, 3, 5, 7]: 


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
values=[value for value,name in zip(data,names) if name != 'Will']
values

[array([-0.93291403,  0.69308151, -1.69953319,  0.35842586]),
 array([-1.24701677, -0.39637787,  1.2460072 , -0.15662888]),
 array([-0.13865239,  0.30514398, -0.76509858,  0.24937611]),
 array([-0.98448328, -0.11798749, -0.50604477,  1.75446948]),
 array([ 0.45848641, -1.05389399,  0.4738683 , -1.07135604])]

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
values=[value for value,name in zip(data,names) if name not in ('Will', 'Joe')]
values

[array([-1.36798537, -0.67271401, -1.04366874,  1.16676944]),
 array([-1.6150955 ,  0.18390397,  1.07749228,  0.94508334])]

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
#method 1:
np.random.randint(low=1, high=15, size=(5,3)) + np.random.random((5,3))
#method 2:
np.random.uniform(1,15, size=(5,3))

array([[ 2.23402105,  7.43485879,  4.01845222],
       [12.59954415, 13.71979135,  6.85906986],
       [13.059308  ,  7.07895467, 14.7266471 ],
       [13.46885545, 12.11655754,  4.0284424 ],
       [ 7.55435438,  9.458034  , 10.4013556 ]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr32=np.random.uniform(1,16, size=(2,2,4))
arr32

array([[[ 5.14456697,  1.37818107,  4.83496972,  7.40854359],
        [ 6.72674182,  1.11839034, 14.41768049,  6.92932892]],

       [[ 1.81360631, 12.01015504, 10.36818431,  9.4622304 ],
        [11.67225041,  2.64729245, 14.19177883,  8.08367829]]])

33. Swap axes of the array you created in Question 32

In [33]:
arr32[[1,0],:]

array([[[ 1.81360631, 12.01015504, 10.36818431,  9.4622304 ],
        [11.67225041,  2.64729245, 14.19177883,  8.08367829]],

       [[ 5.14456697,  1.37818107,  4.83496972,  7.40854359],
        [ 6.72674182,  1.11839034, 14.41768049,  6.92932892]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr34=np.arange(10)
[0 if i <0.5 else i for i in np.sqrt(arr34) ]

[0,
 1.0,
 1.4142135623730951,
 1.7320508075688772,
 2.0,
 2.23606797749979,
 2.449489742783178,
 2.6457513110645907,
 2.8284271247461903,
 3.0]

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
a=np.random.random_sample(12)
b=np.random.random_sample(12)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [39]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,1]=newColumn
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [40]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [47]:
res=np.random.random(20)
np.cumsum(res)

array([0.77133862, 1.70183342, 1.70908548, 2.38819878, 2.78700963,
       2.88090277, 3.82317673, 4.22219779, 4.40763726, 5.24925774,
       5.73030094, 6.50908329, 6.91636891, 6.95152739, 7.63549946,
       8.00142217, 8.26733699, 8.66572457, 8.9093627 , 9.34548419])