# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [9]:
x=np.arange(10).reshape(2,5)
y=np.ones((2,5),dtype=np.int32)
np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [10]:
np.hstack((x,y))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [13]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [25]:
arr=np.arange(16).reshape(4,4)
print("Before: \n",arr)
print("###################")
print("After: ",arr.flatten())

Before: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
###################
After:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [29]:
newArr=np.arange(15)
newArr.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [33]:
arr5D=np.arange(25).reshape(5,5)
np.square(arr5D)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [34]:
arr5D=np.arange(30).reshape(5,6)
np.mean(arr5D)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [35]:
arr5D.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [38]:
np.median(arr5D)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [40]:
arr5D.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [42]:
arr4D=np.arange(16).reshape(4,4)
arr4D.diagonal().sum()

30

## Question:13

### Find the determinant of the previous array in Q12?

In [46]:
np.linalg.det(arr4D)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [48]:
print(np.percentile(arr4D,5))
print(np.percentile(arr4D,95))

0.75
14.25


## Question:15

### How to find if a given array has any null values?

In [62]:
#metode 1
np.isnan(arr4D)
#method 2
has=np.sum(arr4D)
np.isnan(has)

False